### ISSUE TITLE
Modules getting bundled but have extra greyed out headings

### ISSUE THREAD

**Issue by eXigentCoder** [marcj/typedoc-plugin-lerna-packages#10]
Firstly thanks for this plugin, it looks like it's going to be really useful as more and more people use Lerna and mono repos in general!

I'm using the plugin succesfully (mostly) on my [open source project, Dobby](https://github.com/eXigentCoder/dobby), it's definitely grouping the files within into modules but the weird thing is it seems to be leaving behind a greyed out link to the files:
![image](https://user-images.githubusercontent.com/8137674/68483829-eb7b9d00-0244-11ea-956f-0d76bd3afeb5.png)

The full [link to the docs is here](https://exigentcoder.github.io/dobby/), I would appreciate if you could take a look and see if I'm doing something obviously wrong? I did look over [your example source code](https://github.com/marcj/marshal.ts) but from what I'm seeing it should work

**Comment by marcj** [comment]
That's weird. Can it be that you have wrong import statements somewhere? I believe I encountered something similar when I imported a file from another package using relative imports, like `import '../../../core/src/bla.ts'` instead of `import '@vendor/core/bla.ts'`. If not, it's worth to comment out anything and generate the docs again, then successively uncomment peace by peace while generating docs. Eventually you end up finding the line that causes those weird global module names.

**Comment by eXigentCoder** [comment]
Thanks for getting back to me, I took a look and based on your suggestion I commented out absolutely everything in the file `dobby-example/src/create-user` and it still generates the greyed out text.

I then removed the file completely and it goes away. If I create any `*.ts` file in the `src` folder then it generates a greyed out text with that filename so this particular case doesn't seem to be import/export related
